### PR TITLE
Exclude build artifact files from 'git status' output.

### PR DESCRIPTION
**Pull request by rswindell**
This file allows for a clean 'git status' report after running 'make'.

### CODE REVIEW

**Comment by wmcbrine** [comment]
I don't want .gitignore to be in the repo. I have a .gitignore file locally, and the first item in it is... ".gitignore".

**Comment by wmcbrine** [comment]
P.S. See #21 

BTW, this is my actual .gitignore:

.gitignore
.DS_Store
*.o
*.obj
mm
mm.exe

**Comment by rswindell** [comment]
If you have multiple clones of the repo (as I usually do), you'd have to manually replicate that .gitignore file to each clone and deal with keeping them in-sync.

A comment in your README.md would hopefully prevent future wasted time on this matter.

**Comment by andy5995** [comment]
@rswindell I agree for the most part. Even if one doesn't work with multiple clones of a repo. I think .gitignore files are best used for projects/repos that aim to have contributors. I'm not sure if this one does or not (I didn't see a standard contributing doc or mention of contribution guidelines in the Readme). But basically, yeah, it saves time for collaborators in the long-run to have a "centralized" .gitignore, imo. But for projects with single or few maintainers, I'd agree with @wmcbrine that they aren't necessary.

**Comment by andy5995** [comment]
@wmcbrine you might be interested to you know that you don't even need a .gitignore in your local repo.

If you transfer the current contents of your .gitignore to .git/info/exclude, you can then remove your .gitignore.

**Pull request closed without merging**
